name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0-255.2.beta <3.0.0"

dependencies:
  clever_logger:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
