name: clever_logger
description: An easy to use, highly extendable logger library with colorful prints.
version: 1.0.1+1
repository: https://github.com/RoundedInfinity/clever_logger

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"
dependencies:
  ansicolor: ^2.0.1
  logging: ^1.1.0
